name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup NodeJS
        uses: actions/setup-node@v2.1.5
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: Update
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: "Update dist"
          commit_user_name: xtex Bot
          commit_user_email: bot@xtexx.ml
          commit_author: xtex Bot <bot@xtexx.ml>