name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        run: |
          git init
          touch test
          git add test
          git config --global user.email "test-hardwork-action@xtexx.ml"
          git config --global user.name "Test"
          git commit -m "init test repo"
          git branch -m main
      
      - name: Test
        uses: xtexChooser/hardwork-action@main
        with:
          name: Test
          email: test-hardwork-action@xtexx.ml

      - name: Dump
        run: |
          git log --all
